export const FETCH_DATA_LOADING = 'FETCH_DATA_LOADING';
export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';


export const TRENDING_NOW_LOADING = 'TRENDING_NOW_LOADING';
export const TRENDING_NOW = 'TRENDING_NOW';
export const TRENDING_NOW_ERROR = 'TRENDING_NOW_ERROR';


export const TOP_RATED_LOADING = 'TOP_RATED_LOADING';
export const TOP_RATED = 'TOP_RATED';
export const TOP_RATED_ERROR = 'TOP_RATED_ERROR';

export const ROMANCE_LOADING = 'ROMANCE_LOADING';
export const ROMANCE = 'ROMANCE';
export const ROMANCE_ERROR = 'ROMANCE_ERROR';

export const ACTION_LOADING = 'ACTION_LOADING';
export const ACTION = 'ACTION';
export const ACTION_ERROR = 'ACTION_ERROR';

export const HORROR_LOADING = 'HORROR_LOADING';
export const HORROR = 'HORROR';
export const HORROR_ERROR = 'HORROR_ERROR';

export const COMEDY_LOADING = 'COMEDY_LOADING';
export const COMEDY = 'COMEDY';
export const COMEDY_ERROR = 'COMEDY_ERROR';

export const FAMILY_LOADING = 'FAMILY_LOADING';
export const FAMILY = 'FAMILY';
export const FAMILY_ERROR = 'FAMILY_ERROR';

export const MOVIE_DETAILS_LOADING = 'MOVIE_DETAILS_LOADING';
export const MOVIE_DETAILS = 'MOVIE_DETAILS';
export const MOVIE_DETAILS_ERROR = 'MOVIE_DETAILS_ERROR';

export const MOVIE_TRAILER_LOADING = 'MOVIE_TRAILER_LOADING';
export const MOVIE_TRAILER = 'MOVIE_TRAILER';
export const MOVIE_TRAILER_ERROR = 'MOVIE_TRAILER_ERROR';

export const TV_TRAILER_LOADING = 'TV_TRAILER_LOADING';
export const TV_TRAILER = 'TV_TRAILER';
export const TV_TRAILER_ERROR = 'TV_TRAILER_ERROR';

export const TV_DETAILS_LOADING = 'TV_DETAILS_LOADING';
export const TV_DETAILS = 'TV_DETAILS';
export const TV_DETAILS_ERROR = 'TV_DETAILS_ERROR';